{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
{{- end }}
  labels:
    app: {{ template "echoheaders.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "echoheaders.fullname" . }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "echoheaders.fullname" . }}
          servicePort: http
  {{- if .Values.ingress.rules }}
  rules:
    {{- toYaml .Values.ingress.rules | nindent 4 }}
  {{- end }}
{{- end }}