apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "echoheaders.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "echoheaders.fullname" . }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: {{ template "echoheaders.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
